package businessmanager.entities;
// Generated Apr 8, 2017 1:13:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Connections generated by hbm2java
 */
public class Connections  implements java.io.Serializable {


     private Long id;
     private String company;
     private String firstName;
     private String lastName;
     private String address;
     private String address2;
     private String city;
     private String province;
     private String postcode;
     private String country;
     private String contact;
     private String cellPhone;
     private String landPhone;
     private String faxPhone;
     private String email;
     private String skype;
     private String linkedin;
     private String facebook;
     private String twitter;
     private String website;
     private String misc;
     private Boolean customer;
     private Boolean supplier;
     private Boolean taxable1;
     private Boolean taxable2;
     private Set supplierses = new HashSet(0);

    public Connections() {
    }

    public Connections(String company, String firstName, String lastName, String address, String address2, String city, String province, String postcode, String country, String contact, String cellPhone, String landPhone, String faxPhone, String email, String skype, String linkedin, String facebook, String twitter, String website, String misc, Boolean customer, Boolean supplier, Boolean taxable1, Boolean taxable2, Set supplierses) {
       this.company = company;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.address2 = address2;
       this.city = city;
       this.province = province;
       this.postcode = postcode;
       this.country = country;
       this.contact = contact;
       this.cellPhone = cellPhone;
       this.landPhone = landPhone;
       this.faxPhone = faxPhone;
       this.email = email;
       this.skype = skype;
       this.linkedin = linkedin;
       this.facebook = facebook;
       this.twitter = twitter;
       this.website = website;
       this.misc = misc;
       this.customer = customer;
       this.supplier = supplier;
       this.taxable1 = taxable1;
       this.taxable2 = taxable2;
       this.supplierses = supplierses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getCellPhone() {
        return this.cellPhone;
    }
    
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }
    public String getLandPhone() {
        return this.landPhone;
    }
    
    public void setLandPhone(String landPhone) {
        this.landPhone = landPhone;
    }
    public String getFaxPhone() {
        return this.faxPhone;
    }
    
    public void setFaxPhone(String faxPhone) {
        this.faxPhone = faxPhone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSkype() {
        return this.skype;
    }
    
    public void setSkype(String skype) {
        this.skype = skype;
    }
    public String getLinkedin() {
        return this.linkedin;
    }
    
    public void setLinkedin(String linkedin) {
        this.linkedin = linkedin;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getMisc() {
        return this.misc;
    }
    
    public void setMisc(String misc) {
        this.misc = misc;
    }
    public Boolean getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Boolean customer) {
        this.customer = customer;
    }
    public Boolean getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Boolean supplier) {
        this.supplier = supplier;
    }
    public Boolean getTaxable1() {
        return this.taxable1;
    }
    
    public void setTaxable1(Boolean taxable1) {
        this.taxable1 = taxable1;
    }
    public Boolean getTaxable2() {
        return this.taxable2;
    }
    
    public void setTaxable2(Boolean taxable2) {
        this.taxable2 = taxable2;
    }
    public Set getSupplierses() {
        return this.supplierses;
    }
    
    public void setSupplierses(Set supplierses) {
        this.supplierses = supplierses;
    }




}


