package businessmanager.entities;
// Generated Apr 8, 2017 1:13:38 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private Long id;
     private String upc;
     private String code;
     private String shortDescription;
     private String longDescription;
     private String size;
     private String weight;
     private BigDecimal quantity;
     private BigDecimal cost;
     private BigDecimal price;
     private String category;
     private Boolean taxable1;
     private Boolean taxable2;
     private Boolean available;
     private BigDecimal cutoff;
     private Boolean partialSale;
     private Set supplierses = new HashSet(0);

    public Inventory() {
    }

    public Inventory(String upc, String code, String shortDescription, String longDescription, String size, String weight, BigDecimal quantity, BigDecimal cost, BigDecimal price, String category, Boolean taxable1, Boolean taxable2, Boolean available, BigDecimal cutoff, Boolean partialSale, Set supplierses) {
       this.upc = upc;
       this.code = code;
       this.shortDescription = shortDescription;
       this.longDescription = longDescription;
       this.size = size;
       this.weight = weight;
       this.quantity = quantity;
       this.cost = cost;
       this.price = price;
       this.category = category;
       this.taxable1 = taxable1;
       this.taxable2 = taxable2;
       this.available = available;
       this.cutoff = cutoff;
       this.partialSale = partialSale;
       this.supplierses = supplierses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUpc() {
        return this.upc;
    }
    
    public void setUpc(String upc) {
        this.upc = upc;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getShortDescription() {
        return this.shortDescription;
    }
    
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }
    public String getLongDescription() {
        return this.longDescription;
    }
    
    public void setLongDescription(String longDescription) {
        this.longDescription = longDescription;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Boolean getTaxable1() {
        return this.taxable1;
    }
    
    public void setTaxable1(Boolean taxable1) {
        this.taxable1 = taxable1;
    }
    public Boolean getTaxable2() {
        return this.taxable2;
    }
    
    public void setTaxable2(Boolean taxable2) {
        this.taxable2 = taxable2;
    }
    public Boolean getAvailable() {
        return this.available;
    }
    
    public void setAvailable(Boolean available) {
        this.available = available;
    }
    public BigDecimal getCutoff() {
        return this.cutoff;
    }
    
    public void setCutoff(BigDecimal cutoff) {
        this.cutoff = cutoff;
    }
    public Boolean getPartialSale() {
        return this.partialSale;
    }
    
    public void setPartialSale(Boolean partialSale) {
        this.partialSale = partialSale;
    }
    public Set getSupplierses() {
        return this.supplierses;
    }
    
    public void setSupplierses(Set supplierses) {
        this.supplierses = supplierses;
    }




}


