package businessmanager.entities;
// Generated Apr 8, 2017 1:13:38 AM by Hibernate Tools 4.3.1



/**
 * Suppliers generated by hbm2java
 */
public class Suppliers  implements java.io.Serializable {


     private Long id;
     private Connections connections;
     private Inventory inventory;

    public Suppliers() {
    }

    public Suppliers(Connections connections, Inventory inventory) {
       this.connections = connections;
       this.inventory = inventory;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Connections getConnections() {
        return this.connections;
    }
    
    public void setConnections(Connections connections) {
        this.connections = connections;
    }
    public Inventory getInventory() {
        return this.inventory;
    }
    
    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }




}


