package businessmanager.hibernate;
// Generated Apr 22, 2017 1:04:41 PM by Hibernate Tools 4.3.1



/**
 * Countries generated by hbm2java
 */
public class Countries  implements java.io.Serializable {


     private Long id;
     private String country;
     private String twodigitcode;
     private String threedigitcode;
     private String code;
     private String name;

    public Countries() {
    }

    public Countries(String country, String twodigitcode, String threedigitcode, String code, String name) {
       this.country = country;
       this.twodigitcode = twodigitcode;
       this.threedigitcode = threedigitcode;
       this.code = code;
       this.name = name;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getTwodigitcode() {
        return this.twodigitcode;
    }
    
    public void setTwodigitcode(String twodigitcode) {
        this.twodigitcode = twodigitcode;
    }
    public String getThreedigitcode() {
        return this.threedigitcode;
    }
    
    public void setThreedigitcode(String threedigitcode) {
        this.threedigitcode = threedigitcode;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


