package businessmanager.hibernate;
// Generated Apr 22, 2017 1:04:41 PM by Hibernate Tools 4.3.1


import java.sql.Blob;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private Long id;
     private Inventory inventory;
     private String name;
     private String mimeType;
     private Blob document;

    public Document() {
    }

	
    public Document(Inventory inventory) {
        this.inventory = inventory;
    }
    public Document(Inventory inventory, String name, String mimeType, Blob document) {
       this.inventory = inventory;
       this.name = name;
       this.mimeType = mimeType;
       this.document = document;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Inventory getInventory() {
        return this.inventory;
    }
    
    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }
    public Blob getDocument() {
        return this.document;
    }
    
    public void setDocument(Blob document) {
        this.document = document;
    }




}


