package businessmanager.hibernate;
// Generated Apr 22, 2017 1:04:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private Long id;
     private String upc;
     private String code;
     private String description;
     private String note;
     private String size;
     private String weight;
     private BigDecimal quantity;
     private BigDecimal cost;
     private BigDecimal price;
     private String category;
     private Boolean taxable1;
     private Boolean taxable2;
     private Boolean available;
     private BigDecimal cutoff;
     private Boolean partialSale;
     private Integer returnperiodindays;
     private Set documents = new HashSet(0);
     private Set invoiceitemses = new HashSet(0);
     private Set suppliers = new HashSet(0);

    public Inventory() {
    }

    public Inventory(String upc, String code, String description, String note, String size, String weight, BigDecimal quantity, BigDecimal cost, BigDecimal price, String category, Boolean taxable1, Boolean taxable2, Boolean available, BigDecimal cutoff, Boolean partialSale, Integer returnperiodindays, Set documents, Set invoiceitemses, Set suppliers) {
       this.upc = upc;
       this.code = code;
       this.description = description;
       this.note = note;
       this.size = size;
       this.weight = weight;
       this.quantity = quantity;
       this.cost = cost;
       this.price = price;
       this.category = category;
       this.taxable1 = taxable1;
       this.taxable2 = taxable2;
       this.available = available;
       this.cutoff = cutoff;
       this.partialSale = partialSale;
       this.returnperiodindays = returnperiodindays;
       this.documents = documents;
       this.invoiceitemses = invoiceitemses;
       this.suppliers = suppliers;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUpc() {
        return this.upc;
    }
    
    public void setUpc(String upc) {
        this.upc = upc;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Boolean getTaxable1() {
        return this.taxable1;
    }
    
    public void setTaxable1(Boolean taxable1) {
        this.taxable1 = taxable1;
    }
    public Boolean getTaxable2() {
        return this.taxable2;
    }
    
    public void setTaxable2(Boolean taxable2) {
        this.taxable2 = taxable2;
    }
    public Boolean getAvailable() {
        return this.available;
    }
    
    public void setAvailable(Boolean available) {
        this.available = available;
    }
    public BigDecimal getCutoff() {
        return this.cutoff;
    }
    
    public void setCutoff(BigDecimal cutoff) {
        this.cutoff = cutoff;
    }
    public Boolean getPartialSale() {
        return this.partialSale;
    }
    
    public void setPartialSale(Boolean partialSale) {
        this.partialSale = partialSale;
    }
    public Integer getReturnperiodindays() {
        return this.returnperiodindays;
    }
    
    public void setReturnperiodindays(Integer returnperiodindays) {
        this.returnperiodindays = returnperiodindays;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }
    public Set getInvoiceitemses() {
        return this.invoiceitemses;
    }
    
    public void setInvoiceitemses(Set invoiceitemses) {
        this.invoiceitemses = invoiceitemses;
    }
    public Set getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set suppliers) {
        this.suppliers = suppliers;
    }




}


