package businessmanager.hibernate;
// Generated Apr 22, 2017 1:04:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Invoiceitems generated by hbm2java
 */
public class Invoiceitems  implements java.io.Serializable {


     private Long id;
     private Inventory inventory;
     private Invoice invoice;
     private BigDecimal quantity;
     private String code;
     private String description;
     private String note;
     private BigDecimal unitPrice;
     private BigDecimal unitCost;
     private BigDecimal taxable1;
     private BigDecimal taxable2;
     private Integer returnperiodindays;

    public Invoiceitems() {
    }

	
    public Invoiceitems(Invoice invoice, BigDecimal quantity) {
        this.invoice = invoice;
        this.quantity = quantity;
    }
    public Invoiceitems(Inventory inventory, Invoice invoice, BigDecimal quantity, String code, String description, String note, BigDecimal unitPrice, BigDecimal unitCost, BigDecimal taxable1, BigDecimal taxable2, Integer returnperiodindays) {
       this.inventory = inventory;
       this.invoice = invoice;
       this.quantity = quantity;
       this.code = code;
       this.description = description;
       this.note = note;
       this.unitPrice = unitPrice;
       this.unitCost = unitCost;
       this.taxable1 = taxable1;
       this.taxable2 = taxable2;
       this.returnperiodindays = returnperiodindays;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Inventory getInventory() {
        return this.inventory;
    }
    
    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public BigDecimal getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }
    public BigDecimal getTaxable1() {
        return this.taxable1;
    }
    
    public void setTaxable1(BigDecimal taxable1) {
        this.taxable1 = taxable1;
    }
    public BigDecimal getTaxable2() {
        return this.taxable2;
    }
    
    public void setTaxable2(BigDecimal taxable2) {
        this.taxable2 = taxable2;
    }
    public Integer getReturnperiodindays() {
        return this.returnperiodindays;
    }
    
    public void setReturnperiodindays(Integer returnperiodindays) {
        this.returnperiodindays = returnperiodindays;
    }




}


