package businessmanager.hibernate;
// Generated Apr 22, 2017 1:04:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Long id;
     private Contact contact;
     private String invoicenumber;
     private Date invoicedate;
     private String customer;
     private BigDecimal shippingcost;
     private String memo;
     private Boolean ispaid;
     private Boolean isvoid;
     private BigDecimal taxrate1;
     private BigDecimal taxrate2;
     private Boolean isquote;
     private Set invoiceitemses = new HashSet(0);

    public Invoice() {
    }

    public Invoice(Contact contact, String invoicenumber, Date invoicedate, String customer, BigDecimal shippingcost, String memo, Boolean ispaid, Boolean isvoid, BigDecimal taxrate1, BigDecimal taxrate2, Boolean isquote, Set invoiceitemses) {
       this.contact = contact;
       this.invoicenumber = invoicenumber;
       this.invoicedate = invoicedate;
       this.customer = customer;
       this.shippingcost = shippingcost;
       this.memo = memo;
       this.ispaid = ispaid;
       this.isvoid = isvoid;
       this.taxrate1 = taxrate1;
       this.taxrate2 = taxrate2;
       this.isquote = isquote;
       this.invoiceitemses = invoiceitemses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public String getInvoicenumber() {
        return this.invoicenumber;
    }
    
    public void setInvoicenumber(String invoicenumber) {
        this.invoicenumber = invoicenumber;
    }
    public Date getInvoicedate() {
        return this.invoicedate;
    }
    
    public void setInvoicedate(Date invoicedate) {
        this.invoicedate = invoicedate;
    }
    public String getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(String customer) {
        this.customer = customer;
    }
    public BigDecimal getShippingcost() {
        return this.shippingcost;
    }
    
    public void setShippingcost(BigDecimal shippingcost) {
        this.shippingcost = shippingcost;
    }
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    public Boolean getIspaid() {
        return this.ispaid;
    }
    
    public void setIspaid(Boolean ispaid) {
        this.ispaid = ispaid;
    }
    public Boolean getIsvoid() {
        return this.isvoid;
    }
    
    public void setIsvoid(Boolean isvoid) {
        this.isvoid = isvoid;
    }
    public BigDecimal getTaxrate1() {
        return this.taxrate1;
    }
    
    public void setTaxrate1(BigDecimal taxrate1) {
        this.taxrate1 = taxrate1;
    }
    public BigDecimal getTaxrate2() {
        return this.taxrate2;
    }
    
    public void setTaxrate2(BigDecimal taxrate2) {
        this.taxrate2 = taxrate2;
    }
    public Boolean getIsquote() {
        return this.isquote;
    }
    
    public void setIsquote(Boolean isquote) {
        this.isquote = isquote;
    }
    public Set getInvoiceitemses() {
        return this.invoiceitemses;
    }
    
    public void setInvoiceitemses(Set invoiceitemses) {
        this.invoiceitemses = invoiceitemses;
    }




}


