package businessmanager.hibernate;
// Generated Apr 22, 2017 1:04:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Long id;
     private String rolename;
     private Set userroleses = new HashSet(0);

    public Roles() {
    }

    public Roles(String rolename, Set userroleses) {
       this.rolename = rolename;
       this.userroleses = userroleses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    public Set getUserroleses() {
        return this.userroleses;
    }
    
    public void setUserroleses(Set userroleses) {
        this.userroleses = userroleses;
    }




}


