package businessmanager.hibernate;
// Generated Apr 22, 2017 1:04:41 PM by Hibernate Tools 4.3.1



/**
 * Shipaddress generated by hbm2java
 */
public class Shipaddress  implements java.io.Serializable {


     private Long id;
     private Contact contact;
     private String company;
     private String contact_1;
     private String address;
     private String address2;
     private String city;
     private String provence;
     private String postcode;
     private String country;
     private String phone;
     private Boolean isdefault;

    public Shipaddress() {
    }

    public Shipaddress(Contact contact, String company, String contact_1, String address, String address2, String city, String provence, String postcode, String country, String phone, Boolean isdefault) {
       this.contact = contact;
       this.company = company;
       this.contact_1 = contact_1;
       this.address = address;
       this.address2 = address2;
       this.city = city;
       this.provence = provence;
       this.postcode = postcode;
       this.country = country;
       this.phone = phone;
       this.isdefault = isdefault;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getContact_1() {
        return this.contact_1;
    }
    
    public void setContact_1(String contact_1) {
        this.contact_1 = contact_1;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvence() {
        return this.provence;
    }
    
    public void setProvence(String provence) {
        this.provence = provence;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Boolean getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(Boolean isdefault) {
        this.isdefault = isdefault;
    }




}


