package businessmanager.hibernate;
// Generated Apr 22, 2017 1:04:41 PM by Hibernate Tools 4.3.1



/**
 * Userroles generated by hbm2java
 */
public class Userroles  implements java.io.Serializable {


     private Long id;
     private Roles roles;
     private Users users;

    public Userroles() {
    }

    public Userroles(Roles roles, Users users) {
       this.roles = roles;
       this.users = users;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


