package businessmanager.hibernate;
// Generated Apr 22, 2017 1:04:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Long id;
     private byte[] userid;
     private String password;
     private String username;
     private Set userroleses = new HashSet(0);

    public Users() {
    }

	
    public Users(byte[] userid) {
        this.userid = userid;
    }
    public Users(byte[] userid, String password, String username, Set userroleses) {
       this.userid = userid;
       this.password = password;
       this.username = username;
       this.userroleses = userroleses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public byte[] getUserid() {
        return this.userid;
    }
    
    public void setUserid(byte[] userid) {
        this.userid = userid;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Set getUserroleses() {
        return this.userroleses;
    }
    
    public void setUserroleses(Set userroleses) {
        this.userroleses = userroleses;
    }




}


